# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "buoyantair's blog"
tagline:             'Practice makes man perfect'
description:         "This is @buoyantair's blog, @buoyantair posts about their programming experience & tutorials here."
url:                 https://buoyantair.github.io/blog/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Buoyant Air  
  url:               https://twitter.com/buoyantair
  email:             buoyantair@gmail.com

# Custom vars
version:             1.0.0
